workflows:
  ios-workflow:
    name: iOS Workflow

    integrations:
      app_store_connect: API Key

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.danielwarnock.TenderTimelinePlanner

    scripts:
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "TenderTimelinePlanner.xcodeproj" \
            --scheme "TenderTimelinePlanner"

    publishing:
      app_store_connect:
        submit_to_testflight: true
