workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      groups:
        - AppStoreConnect
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.danielwarnock.tendertimelineapp

    scripts:
      - name: Set up code signing
        script: |
          xcode-project use-profiles --archive-method app-store
          ls -la /Users/builder/

      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "TenderTimelinePlanner.xcodeproj" \
            --scheme "TenderTimelinePlanner" \
            --archive-method app-store

    publishing:
      app_store_connect:
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
