workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.danielwarnock.tendertimelineapp
      vars:
        XCODE_PROJECT: TenderTimelinePlanner.xcodeproj
        XCODE_SCHEME: TenderTimelinePlanner
      xcode: latest

    scripts:
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build ipa
        script: |
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
